language: cpp
compiler:
    - gcc
    - clang
before_script:
    - sudo apt-get install libboost-dev
    - sudo apt-get install llvm-2.8-dev
    - sudo apt-get install mesa-common-dev
    - sudo apt-get install freeglut3-dev
script: make && make test
branches:
    only:
        - master
notifications:
    recipients:
        - onlyuser@gmail.com
    email:
        on_success: change
        on_failure: always
